FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements_bot.txt .
RUN pip install --no-cache-dir -r requirements_bot.txt

COPY . .

CMD ["python", "tg_bot.py"]
